package netgloo.models;

import javax.persistence.Cacheable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;



/**
 * An entity User composed by three fields (id, email, name). The Entity
 * annotation indicates that this class is a JPA entity. The Table annotation
 * specifies the name for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "user")
public class User {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer userId;

	@NotNull
	private String email;

	@NotNull
	private String userPassword;

	@NotNull
	private String userName;

	@NotNull
	private String userSurname;

	@NotNull
	private String userBirthDate;

	@NotNull
	private String userRegistrationDate;

	@NotNull
	private String userRole;

	@NotNull
	private Boolean userStatus;
	
	public User() {
		super();
	}


	public User(String email, String user_password, String user_name, String user_surname, String user_birth_date,
			String user_registration_date, String user_role, Boolean userStatus) {
		super();
		this.email = email;
		this.userPassword = user_password;
		this.userName = user_name;
		this.userSurname = user_surname;
		this.userBirthDate = user_birth_date;
		this.userRegistrationDate = user_registration_date;
		this.userRole = user_role;
		this.userStatus = userStatus;
	}
	

	public User(Integer user_id) {
		super();
		this.userId = user_id;
	}

	public Integer getUser_id() {
		return userId;
	}

	public void setUser_id(Integer user_id) {
		this.userId = user_id;
	}

	
	
	

	public Integer getUserId() {
		return userId;
	}


	public void setUserId(Integer userId) {
		this.userId = userId;
	}


	public String getUserPassword() {
		return userPassword;
	}


	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}


	public String getUserName() {
		return userName;
	}


	public void setUserName(String userName) {
		this.userName = userName;
	}


	public String getUserSurname() {
		return userSurname;
	}


	public void setUserSurname(String userSurname) {
		this.userSurname = userSurname;
	}


	public String getUserBirthDate() {
		return userBirthDate;
	}


	public void setUserBirthDate(String userBirthDate) {
		this.userBirthDate = userBirthDate;
	}


	public String getUserRegistrationDate() {
		return userRegistrationDate;
	}


	public void setUserRegistrationDate(String userRegistrationDate) {
		this.userRegistrationDate = userRegistrationDate;
	}


	public String getUserRole() {
		return userRole;
	}


	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}


	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUser_password() {
		return userPassword;
	}

	public void setUser_password(String user_password) {
		this.userPassword = user_password;
	}

	public String getUser_name() {
		return userName;
	}

	public void setUser_name(String user_name) {
		this.userName = user_name;
	}

	public String getUser_surname() {
		return userSurname;
	}

	public void setUser_surname(String user_surname) {
		this.userSurname = user_surname;
	}



	public String getUser_birth_date() {
		return userBirthDate;
	}

	public void setUser_birth_date(String user_birth_date) {
		this.userBirthDate = user_birth_date;
	}

	public String getUser_registration_date() {
		return userRegistrationDate;
	}

	public void setUser_registration_date(String user_registration_date) {
		this.userRegistrationDate = user_registration_date;
	}

	public String getUser_role() {
		return userRole;
	}

	public void setUser_role(String user_role) {
		this.userRole = user_role;
	}


	public Boolean getUserStatus() {
		return userStatus;
	}


	public void setUserStatus(Boolean userStatus) {
		this.userStatus = userStatus;
	}

	
	
	
	/*
	 * 
	 * 
	 * // An autogenerated id (unique for each user in the db)
	 * 
	 * @Id
	 * 
	 * @GeneratedValue(strategy = GenerationType.AUTO) private long id;
	 * 
	 * // The user's email
	 * 
	 * @NotNull private String email;
	 * 
	 * // The user's name
	 * 
	 * @NotNull private String name;
	 * 
	 * // ------------------------ // PUBLIC METHODS // ------------------------
	 * 
	 * public User() { }
	 * 
	 * public User(long id) { this.id = id; }
	 * 
	 * public User(String email, String name) { this.email = email; this.name =
	 * name; }
	 * 
	 * // Getter and setter methods
	 * 
	 * public long getId() { return id; }
	 * 
	 * public void setId(long value) { this.id = value; }
	 * 
	 * public String getEmail() { return email; }
	 * 
	 * public void setEmail(String value) { this.email = value; }
	 * 
	 * public String getName() { return name; }
	 * 
	 * public void setName(String value) { this.name = value; }
	 */

} // class User
